/**
* CinemaSurf API (using TMDB)
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models


/**
 * 
 * @param id 
 * @param title 
 * @param homepage 
 * @param overview 
 * @param poster_path 
 * @param release_date 
 * @param revenue 
 * @param runtime 
 * @param vote_average 
 * @param vote_count 
 */
data class Movie (
    val id: kotlin.Int? = null,
    val title: kotlin.String? = null,
    val homepage: kotlin.String? = null,
    val overview: kotlin.String? = null,
    val poster_path: kotlin.String? = null,
    val release_date: java.time.LocalDateTime? = null,
    val revenue: kotlin.Int? = null,
    val runtime: kotlin.Int? = null,
    val vote_average: java.math.BigDecimal? = null,
    val vote_count: kotlin.Int? = null
) {

}

